@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

package "Commands" #F4F6F6 {
Class CombinedCommand
Class CompatibleCommand
}

package "Parsers" #F4F6F6 {
Class CombinedCommandParser
Class CompatibleCommandParser
Class AddressBookParser
}

}

package "Model (Person Predicates)" as ModelPackage #F4F6F6 {
Class CombinedPredicate
Class NameExactMatchPredicate
Class OrganContainsSubstringPredicate
Class BloodTypeRecipientCompatiblePredicate
Class BloodTypeCompatibilityPredicate
}

CombinedCommandParser -down-> CombinedCommand : creates
CompatibleCommandParser -down-> CompatibleCommand : creates
AddressBookParser -down-> CombinedCommandParser : uses
AddressBookParser -down-> CompatibleCommandParser : uses

CombinedCommand -down-> "1" CombinedPredicate : uses
CompatibleCommand -down-> "1" BloodTypeCompatibilityPredicate : uses

CombinedCommandParser .down.> CombinedPredicate : creates
CombinedPredicate -down-> "0..1" NameExactMatchPredicate : contains
CombinedPredicate -down-> "0..1" OrganContainsSubstringPredicate : contains
CombinedPredicate -down-> "0..1" BloodTypeRecipientCompatiblePredicate : contains

@enduml

