@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":CompatibilityEngine" as compatibilityEngine COMPATIBILITYENGINE_COLOR
Participant ":Model" as model MODEL_COLOR

user -[USER_COLOR]> ui : "addPair RecipientA DonorA"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("addPair RecipientA DonorA")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : addPair(RecipientA, DonorA)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model MODEL_COLOR

logic -[LOGIC_COLOR]> compatibilityEngine : findSwap()
activate compatibilityEngine COMPATIBILITYENGINE_COLOR

compatibilityEngine -[COMPATIBILITYENGINE_COLOR]> model : getPairs()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> compatibilityEngine
deactivate model MODEL_COLOR

compatibilityEngine -[COMPATIBILITYENGINE_COLOR]-> logic
deactivate compatibilityEngine COMPATIBILITYENGINE_COLOR

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
